<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Politique de Confidentialité & CGU - ComImmo</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.7;
            padding: 2em;
            max-width: 800px;
            margin: 2em auto;
            color: #333;
            background-color: #f9f9f9;
        }
        h1, h2, h3 {
            color: #111;
        }
        h1 {
            text-align: center;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }
        h2 {
            margin-top: 2em;
        }
        a {
            color: #007aff;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        strong {
            font-weight: 600;
        }
        ul {
            padding-left: 20px;
        }
    </style>
</head>
<body>

    <h1>Mentions Légales et Conditions Générales d'Utilisation - ComImmo</h1>

    <h2>Préambule</h2>
    <p>
        La présente application <strong>ComImmo</strong> est éditée par <strong>L'héritier Thibault</strong>. Pour toute information, l’utilisateur peut contacter l’éditeur en écrivant à <strong>ComImmo.app@outlook.com</strong>.
    </p>
    <p>
        L’utilisation de l’application « ComImmo », ci-après nommée « l’Application », est soumise au respect des présentes Conditions Générales d’Utilisation, ci-après nommées « CGU ». En téléchargeant et en utilisant l'Application, tout utilisateur, ci-après nommé « l'Utilisateur », reconnaît avoir pris connaissance des présentes CGU et les accepter sans réserve.
    </p>

    <h2>Article 1 : OBJET</h2>
    <p>
        Les présentes CGU ont pour objet de définir les modalités et conditions dans lesquelles l’Utilisateur accède à l’Application et utilise les Services proposés. L'éditeur se réserve le droit de modifier à tout moment les présentes CGU, notamment pour les adapter aux évolutions de l'Application.
    </p>

    <h2>Article 2 : DÉFINITIONS</h2>
    <ul>
        <li><strong>Application :</strong> Le programme logiciel « ComImmo », édité et exploité par <strong>[Votre Nom ou Nom de votre entreprise]</strong>, destiné à la gestion d'activité pour les professionnels de l'immobilier.</li>
        <li><strong>Utilisateur :</strong> Toute personne physique ou morale qui télécharge, installe et utilise l’Application.</li>
        <li><strong>Compte :</strong> L'espace personnel de l'Utilisateur, accessible via des identifiants, lui permettant d'utiliser les Services de l'Application.</li>
        <li><strong>Contenus :</strong> Ensemble des informations et données que l’Utilisateur saisit, génère et gère depuis son Compte (informations de ventes, commissions, factures, etc.).</li>
        <li><strong>Service(s) :</strong> L'ensemble des fonctionnalités mises à disposition de l'Utilisateur par l'Application.</li>
    </ul>

    <h2>Article 3 : PRÉSENTATION DES SERVICES</h2>
    <p>
        L'Application ComImmo est un outil de gestion destiné aux professionnels de l'immobilier. Elle propose notamment les Services suivants :
    </p>
    <ul>
        <li>Création et gestion d'un Compte personnel sécurisé.</li>
        <li>Saisie, suivi et gestion des ventes immobilières.</li>
        <li>Calcul automatisé des commissions et salaires.</li>
        <li>Génération de documents (factures, récapitulatifs).</li>
    </ul>

    <h2>Article 4 : ACCÈS ET PRÉ-REQUIS TECHNIQUES</h2>
    <p>
        L'accès à l'Application nécessite un Compte. L'Utilisateur est responsable de la confidentialité de ses identifiants (e-mail et mot de passe). L'Application est accessible depuis les magasins d'applications sur des terminaux mobiles compatibles (smartphones, tablettes).
    </p>

    <h2>Article 5 : CHARTE DE CONFIDENTIALITÉ ET DONNÉES PERSONNELLES</h2>
    <p>
        Le respect de la vie privée de l'Utilisateur est une priorité. Cette charte détaille le traitement des données personnelles dans le cadre de l'utilisation de l'Application, conformément au Règlement Général sur la Protection des Données (RGPD).
    </p>
    
    <h3>5.1 Données collectées</h3>
    <p>Dans le cadre de la fourniture des Services, nous collectons les données suivantes :</p>
    <ul>
        <li><strong>Données d'identification :</strong> L'adresse e-mail et le mot de passe (chiffré) fournis par l'Utilisateur lors de la création de son Compte.</li>
        <li><strong>Contenus professionnels :</strong> Toutes les données que l'Utilisateur saisit volontairement dans l'Application, telles que les informations relatives aux ventes, clients, commissions, salaires et coordonnées bancaires.</li>
        <li><strong>Données techniques :</strong> Des données anonymisées sur l'utilisation de l'Application (type d'appareil, version de l'OS, rapports de plantage) peuvent être collectées à des fins de maintenance et d'amélioration du Service.</li>
    </ul>
    
    <h3>5.2 Finalités du traitement</h3>
    <p>Les données collectées sont utilisées exclusivement pour les finalités suivantes :</p>
    <ul>
        <li>Fournir, gérer et maintenir les Services de l'Application.</li>
        <li>Gérer les Comptes Utilisateurs et assurer leur authentification.</li>
        <li>Assurer la sécurité de l'Application et prévenir les fraudes.</li>
        <li>Communiquer avec l'Utilisateur pour des raisons techniques ou administratives.</li>
    </ul>

    <h3>5.3 Hébergement et sécurité des données (Firebase)</h3>
    <p>
        L'Application utilise les services de <strong>Firebase</strong>, une plateforme développée par Google, pour :
    </p>
    <ul>
        <li><strong>L'authentification des Utilisateurs</strong> (Firebase Authentication).</li>
        <li><strong>Le stockage et la synchronisation des données</strong> en temps réel (Cloud Firestore / Realtime Database).</li>
    </ul>
    <p>
        Les données de l'Utilisateur sont donc hébergées et traitées sur l'infrastructure sécurisée de Google. L'éditeur s'engage à mettre en œuvre les mesures de sécurité appropriées pour protéger les Contenus, mais ne saurait être tenu responsable des failles de sécurité relevant du fournisseur tiers. Pour plus d'informations, l'Utilisateur peut consulter la politique de confidentialité de Google : <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.
    </p>
    
    <h3>5.4 Droits de l'Utilisateur</h3>
    <p>
        Conformément à la loi, l'Utilisateur dispose d'un droit d'accès, de rectification, de suppression (droit à l'oubli) et de portabilité de ses données. L'Utilisateur peut exercer ces droits en contactant l'éditeur à l'adresse e-mail <strong>[Votre adresse e-mail de contact]</strong>.
    </p>
    
    <h3>5.5 Durée de conservation</h3>
    <p>
        Les données personnelles sont conservées tant que le Compte de l'Utilisateur est actif. En cas de suppression du Compte, les données seront supprimées de nos bases de données dans un délai raisonnable, sauf obligation légale de conservation.
    </p>

    <h2>Article 6 : OBLIGATIONS DE L'UTILISATEUR</h2>
    <p>L'Utilisateur s'engage à :</p>
    <ul>
        <li>Fournir des informations exactes lors de la création de son Compte.</li>
        <li>Maintenir la confidentialité de son mot de passe et ne pas le divulguer.</li>
        <li>Utiliser l'Application conformément à sa finalité et dans le respect des lois en vigueur.</li>
        <li>Être seul responsable des Contenus qu'il saisit et gère dans l'Application.</li>
    </ul>

    <h2>Article 7 : LIMITATION DE RESPONSABILITÉ</h2>
    <p>
        L'éditeur met tout en œuvre pour assurer un accès permanent et un fonctionnement optimal de l'Application. Toutefois, sa responsabilité ne saurait être engagée en cas d'indisponibilité due à des opérations de maintenance, des pannes techniques, des cas de force majeure ou des faits de tiers. L'éditeur ne pourra être tenu responsable des dommages indirects, tels que la perte de données ou de chiffre d'affaires, résultant de l'utilisation ou de l'impossibilité d'utiliser l'Application.
    </p>

    <h2>Article 8 : PROPRIÉTÉ INTELLECTUELLE</h2>
    <p>
        L'ensemble des éléments constituant l'Application (textes, graphismes, logos, code source, etc.) sont la propriété exclusive de <strong>[Votre Nom ou Nom de votre entreprise]</strong> et sont protégés par les lois relatives à la propriété intellectuelle. Toute reproduction, même partielle, est strictement interdite sans autorisation écrite préalable.
    </p>

    <h2>Article 9 : LOI APPLICABLE ET JURIDICTION</h2>
    <p>
        Les présentes CGU sont soumises au droit français. En cas de litige, et après une tentative de résolution amiable, compétence exclusive est attribuée aux tribunaux compétents de <strong>[Ville de votre tribunal de commerce, ex: Paris]</strong>.
    </p>

</body>
</html>
